#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Prime number calculation tool', 1.0);
$application->add(new PrimeFactorCommand(new PrimeFactors()));
$application->run();